import { afterEach, describe, expect, it, vi } from "vitest";
import fs from "fs";
import os from "os";
import path from "path";
import { createRequire } from "module";
import { fileURLToPath } from "url";

const require = createRequire(import.meta.url);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.join(__dirname, "../../..");
const generator = require(
  path.join(PROJECT_ROOT, "tools/audio-generator/elevenlabs/generate.js")
);
const SoundConfig = require(
  path.join(PROJECT_ROOT, "client/js/audio/config/SoundConfig.js")
);

const temporaryDirectories = [];
const silentLogger = {
  log: vi.fn(),
  error: vi.fn(),
};

function makeTempDirectory() {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "galaxy-miner-elevenlabs-test-"));
  temporaryDirectories.push(directory);
  return directory;
}

function fakeMp3(label = "audio") {
  return Buffer.from(`ID3${label}`);
}

function audioResponse(buffer = fakeMp3(), status = 200, headers = {}) {
  return new Response(buffer, {
    status,
    headers: { "content-type": "audio/mpeg", ...headers },
  });
}

function expandConfigFiles(config) {
  const files = [];
  if (typeof config.file === "string") files.push(config.file);
  if (
    typeof config.variationPattern === "string" &&
    Number.isInteger(config.variations)
  ) {
    for (let index = 1; index <= config.variations; index++) {
      files.push(
        config.variationPattern.replace(
          "{index}",
          String(index).padStart(2, "0")
        )
      );
    }
  }
  return files;
}

afterEach(() => {
  vi.clearAllMocks();
  while (temporaryDirectories.length > 0) {
    fs.rmSync(temporaryDirectories.pop(), { recursive: true, force: true });
  }
});

describe("ElevenLabs prompt catalog", () => {
  it("validates every prompt, duration, ID, and output path", () => {
    expect(generator.validateCatalog()).toEqual([]);
  });

  it("covers every runtime player and NPC weapon fallback and variation", () => {
    const expected = new Set();
    for (const [soundId, config] of Object.entries(SoundConfig)) {
      if (soundId.startsWith("weapon_fire_") || soundId.startsWith("npc_weapon_")) {
        expandConfigFiles(config).forEach((filename) => expected.add(filename));
      }
    }

    const generated = new Set(
      generator.getCategoryAssets("weapons").map((asset) => asset.relativePath)
    );

    expect(expected.size).toBe(42);
    expect(generated).toEqual(expected);
  });

  it("aggregates all 20 UI assets and excludes destruction from safe collections", () => {
    const uiCategories = generator.COLLECTIONS.ui;
    const uiAssets = uiCategories.flatMap((category) =>
      generator.getCategoryAssets(category)
    );

    expect(uiAssets).toHaveLength(20);
    expect(new Set(uiAssets.map((asset) => asset.relativePath)).size).toBe(20);
    expect(uiAssets.every((asset) => asset.relativePath.startsWith("ui/"))).toBe(true);

    for (const categoryNames of Object.values(generator.COLLECTIONS)) {
      expect(categoryNames).not.toContain("destruction");
      expect(categoryNames).not.toContain("destruction_variants");
      expect(categoryNames).not.toContain("base_destruction");
    }
  });
});

describe("ElevenLabs request contract", () => {
  it("puts output_format in the query and pins the v2 request controls", () => {
    const sound = generator.SOUNDS.weapons.sounds[0];
    const request = generator.buildApiRequest(sound, {
      apiUrl: "https://example.test/v1/sound-generation",
      outputFormat: "mp3_44100_128",
      modelId: "eleven_text_to_sound_v2",
      promptInfluence: 0.55,
    });

    const url = new URL(request.url);
    expect(url.searchParams.get("output_format")).toBe("mp3_44100_128");
    expect(request.body).toEqual({
      text: sound.prompt,
      duration_seconds: 0.5,
      prompt_influence: 0.55,
      model_id: "eleven_text_to_sound_v2",
      loop: false,
    });
    expect(request.body).not.toHaveProperty("output_format");
  });

  it("fails before fetch or writes when the API key is missing", async () => {
    const outputBase = makeTempDirectory();
    const fetchImpl = vi.fn();
    const sound = generator.expandSoundAssets(
      generator.SOUNDS.weapons.sounds[0],
      false
    )[0];

    const result = await generator.generateSound(sound, "weapons", {
      apiKey: "",
      outputBase,
      forceRegenerate: true,
      fetchImpl,
      maxAttempts: 1,
      logger: silentLogger,
      audioProcessor: (audio) => audio,
    });

    expect(result.success).toBe(false);
    expect(result.error).toContain("ELEVENLABS_API_KEY");
    expect(fetchImpl).not.toHaveBeenCalled();
    expect(fs.readdirSync(outputBase)).toEqual([]);
  });

  it("writes validated generated bytes and sends no key in the JSON body", async () => {
    const outputBase = makeTempDirectory();
    const generatedAudio = fakeMp3("generated-result");
    const fetchImpl = vi.fn(async () => audioResponse(generatedAudio));
    const sound = generator.expandSoundAssets(
      generator.SOUNDS.weapons.sounds[0],
      false
    )[0];

    const result = await generator.generateSound(sound, "weapons", {
      apiKey: "test-key-not-secret",
      outputBase,
      forceRegenerate: true,
      fetchImpl,
      maxAttempts: 1,
      logger: silentLogger,
      audioProcessor: (audio) => audio,
    });

    expect(result.success).toBe(true);
    expect(fs.readFileSync(result.outputPath)).toEqual(generatedAudio);
    expect(fetchImpl).toHaveBeenCalledTimes(1);
    const [, options] = fetchImpl.mock.calls[0];
    expect(JSON.parse(options.body)).not.toHaveProperty("apiKey");
    expect(options.headers["xi-api-key"]).toBe("test-key-not-secret");
  });

  it("retries rate limits and then accepts a valid MP3", async () => {
    const fetchImpl = vi
      .fn()
      .mockResolvedValueOnce(
        new Response("rate limited", {
          status: 429,
          headers: { "retry-after": "0" },
        })
      )
      .mockResolvedValueOnce(audioResponse(fakeMp3("retry-success")));
    const sleep = vi.fn(async () => {});

    const result = await generator.requestAudio(
      generator.SOUNDS.weapons.sounds[0],
      generator.getRuntimeOptions({
        apiKey: "test-key-not-secret",
        fetchImpl,
        sleep,
        maxAttempts: 2,
      })
    );

    expect(generator.looksLikeMp3(result)).toBe(true);
    expect(fetchImpl).toHaveBeenCalledTimes(2);
    expect(sleep).toHaveBeenCalledWith(0);
  });

  it("preserves an existing asset when the API response fails validation", async () => {
    const outputBase = makeTempDirectory();
    const outputDir = path.join(outputBase, "weapons");
    const sound = generator.expandSoundAssets(
      generator.SOUNDS.weapons.sounds[0],
      false
    )[0];
    const outputPath = path.join(outputDir, sound.filename);
    fs.mkdirSync(outputDir, { recursive: true });
    fs.writeFileSync(outputPath, fakeMp3("original"));

    const result = await generator.generateSound(sound, "weapons", {
      apiKey: "test-key-not-secret",
      outputBase,
      forceRegenerate: true,
      fetchImpl: vi.fn(async () => audioResponse(Buffer.from("not-mp3"))),
      maxAttempts: 1,
      logger: silentLogger,
      audioProcessor: (audio) => audio,
    });

    expect(result.success).toBe(false);
    expect(fs.readFileSync(outputPath)).toEqual(fakeMp3("original"));
  });

  it("passes the active cue duration to ffmpeg trimming", () => {
    const calls = [];
    const sound = generator.SOUNDS.weapons.sounds[0];
    const result = generator.trimMp3ToActiveDuration(fakeMp3("source"), sound, {
      spawnSyncImpl(command, args) {
        calls.push({ command, args });
        fs.writeFileSync(args.at(-1), fakeMp3("trimmed"));
        return { status: 0, stderr: "" };
      },
    });

    expect(generator.looksLikeMp3(result)).toBe(true);
    expect(calls).toHaveLength(1);
    expect(calls[0].command).toBe("ffmpeg");
    const filter = calls[0].args[calls[0].args.indexOf("-af") + 1];
    expect(filter).toContain("silenceremove=");
    expect(filter).toContain("atrim=duration=0.090");
    expect(filter).toContain("loudnorm=I=-18:TP=-3:LRA=7");
  });
});

describe("ElevenLabs CLI", () => {
  it("dry-runs the complete weapon/UI collection without a key or writes", async () => {
    const outputBase = makeTempDirectory();
    const exitCode = await generator.main(
      [
        "--dry-run",
        "--collection",
        "weapon-ui",
        "--output-dir",
        outputBase,
      ],
      { apiKey: "", logger: silentLogger }
    );

    expect(exitCode).toBe(0);
    expect(fs.readdirSync(outputBase)).toEqual([]);
    expect(silentLogger.log).toHaveBeenCalledWith(expect.stringContaining("62"));
  });

  it("returns a nonzero code for an unknown selection", async () => {
    const exitCode = await generator.main(
      ["--collection", "not-a-collection"],
      { logger: silentLogger }
    );
    expect(exitCode).toBe(1);
  });
});
